# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development, :test do
  gem 'rspec', '~> 3.10'
  gem 'rubocop', '~> 1.23'
  gem "simplecov", require: false
  gem "simplecov-console", require: false
end
